function filePath = OpenVideoFile()
videoFilePath = fullfile(pwd, 'video\traffic.avi');
[filename, pathname, filterindex] = uigetfile( ...
    {  '*.avi','视频文件 (*.avi)'; ...
    '*.mpeg','视频文件 (*.mpeg)'; ...
    '*.*',  '所有文件 (*.*)'}, ...
    '选择视频文件', ...
    'MultiSelect', 'off', ...
    videoFilePath);
filePath = 0;
if isequal(filename, 0) || isequal(pathname, 0)
    return;
end
filePath = fullfile(pathname, filename);
